### ISSUE TITLE
跟nncron这个软件比有什么优势

### ISSUE THREAD

**Issue by chaegumi** [shuiguang/windows-crontab#1]
如题，就是想要问问

**Comment by shuiguang** [comment]
刚才试用了nncron，界面功能确实很强大，可是我只找到了windows版本。windows-crontab是workerman-crontab的移植版本，兼容linux的crontab语法，处理小型定时任务足以，并且这个应用和workerman的源码都是完全开源的，你可以定制属于自己的功能。
